# Generated by Django 3.0.4 on 2020-04-01 09:49

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_site', '0008_auto_20200401_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/static_site/media/static_site/products/%Y/%m/'), upload_to=''),
        ),
    ]
