# Generated by Django 3.0.4 on 2020-04-01 10:11

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_site', '0010_auto_20200401_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/'), upload_to=''),
        ),
    ]
