# Generated by Django 3.0.4 on 2020-04-01 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('static_site', '0017_auto_20200401_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='static_site.Unit'),
            preserve_default=False,
        ),
    ]
