# Generated by Django 3.0.4 on 2020-04-08 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static_site', '0018_product_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
    ]
