# Generated by Django 3.0.4 on 2020-04-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_site', '0029_auto_20200428_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='details',
            field=models.CharField(default='Small', max_length=120),
        ),
    ]
