# Generated by Django 3.0.4 on 2020-04-28 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static_site', '0030_orderitem_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
