# Generated by Django 3.0.4 on 2020-04-28 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static_site', '0031_auto_20200428_1957'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
