# Generated by Django 3.0.4 on 2020-04-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_site', '0034_auto_20200429_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='addressee',
            field=models.CharField(default='Anonymous', max_length=350),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='location',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
