# Generated by Django 3.0.4 on 2020-05-04 08:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('static_site', '0037_auto_20200504_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_placed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
