# Generated by Django 3.0.4 on 2020-05-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_site', '0038_auto_20200504_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_placed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
