# Generated by Django 3.0.4 on 2020-05-08 12:19

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('static_site', '0039_auto_20200504_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(default='Small', max_length=120)),
                ('quantity', models.IntegerField(default=0)),
                ('current_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='phone_number',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='variety',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Phone_Number',
        ),
        migrations.AddField(
            model_name='variety',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variety', to='static_site.Product'),
        ),
        migrations.AddField(
            model_name='stock',
            name='product',
            field=models.ManyToManyField(related_name='in_stock', to='static_site.Product'),
        ),
        migrations.AddField(
            model_name='stock',
            name='variety',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='static_site.Variety'),
        ),
    ]
