# Generated by Django 3.0.4 on 2020-05-08 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static_site', '0042_auto_20200508_1308'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('product', 'variety', 'details')},
        ),
    ]
