# Generated by Django 3.0.4 on 2020-05-08 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static_site', '0044_auto_20200508_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='discount',
        ),
    ]
