# Generated by Django 3.0.4 on 2020-05-08 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static_site', '0045_remove_stock_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='current_price',
        ),
    ]
