# Generated by Django 3.0.4 on 2020-05-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_site', '0046_remove_stock_current_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
